const swaggerAutogen = require('swagger-autogen')()

const outputFile = './swagger_output.json'
const endpointsFiles = ['./routes/api.route.js',]

const doc = {
    info: {
        version: "1.0.0",
        title: "OSW APIs",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    // host: "localhost:7001",
    host: "nodejs-projects-osw-backend.un7jm4.easypanel.host",
    schemes: ['https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [{
        "name": "One Smart World(OSW)",
        "description": "API for OSW Portal"
    }],
    basePath: '/api',
    securityDefinitions: {
        bearerAuth:{
            type: 'apiKey',
            name: 'authorization',
            scheme: 'bearer',
            in: 'header',
            "description":"Ex: Bearer 14213841804v323v3...."
        },
    },
    security: { bearerAuth: [] }
}

swaggerAutogen(outputFile, endpointsFiles,doc)